import { ArrowUpRight, BarChart3, Clock3, Radar, Radio, TrendingUp } from 'lucide-react'
import type { ScannerResponse, ScannerRow, VolumeLevel } from '../types'
import { DirectionValue, SectionHeading, StatCard, formatNumber, formatPrice } from '../components/ui'

function sideLevels(row: ScannerRow, side: 'above' | 'below'): VolumeLevel[] {
  return (row[`${side}Levels`] || []).slice(0, 3)
}
function levels(row: ScannerRow, side: 'above' | 'below') { const found = sideLevels(row, side); return found.length ? found.map((level) => formatPrice(level.price)).join(' · ') : '—' }

export function Dashboard({ response, loading, onOpenScanner, onSelect }: { response: ScannerResponse | null; loading: boolean; onOpenScanner: () => void; onSelect: (symbol: string) => void }) {
  const rows = response?.rows || []; const overview = response?.overview; const leaders = rows.filter((row) => sideLevels(row, 'above').length || sideLevels(row, 'below').length).slice(0, 8)
  const total = overview?.scanned ?? rows.length; const available = overview?.withLevels ?? leaders.length; const missing = overview?.missing ?? Math.max(total - available, 0)
  return <div className="dashboard-page"><div className="page-intro"><div><div className="eyebrow">NSE F&amp;O / MARKET OVERVIEW</div><h1>Reference levels<span className="accent">.</span></h1><p>Monitor previous-session opens, volume concentration above and below them, and the quality of each observation.</p></div><button className="button primary" onClick={onOpenScanner}><Radar size={16} />Open scanner <ArrowUpRight size={15} /></button></div>
    <div className="dashboard-note"><div className="note-icon"><Radio size={16} /></div><div><strong>NSE Market Analytics</strong><span>{response?.date || 'Selected session'} · Previous session {response?.previousSessionDate || '—'} · Live exchange snapshots</span></div></div>
    <div className="stat-grid"><StatCard label="Instruments scanned" value={loading ? '—' : String(total)} detail="Selected universe" icon={<BarChart3 size={16} />} /><StatCard label="With reference levels" value={loading ? '—' : String(available)} detail={`${missing} partial or missing`} tone="accent" icon={<TrendingUp size={16} />} /><StatCard label="Above / below observations" value={loading ? '—' : `${overview?.above ?? '—'} / ${overview?.below ?? '—'}`} detail="Relative to previous open" tone="positive" icon={<Radio size={16} />} /><StatCard label="Session Status" value={response?.sessionStatus || 'ACTIVE'} detail="National Stock Exchange" tone="warning" icon={<Clock3 size={16} />} /></div>
    <div className="dashboard-grid"><section className="panel ranking-panel"><SectionHeading eyebrow="LEVEL COVERAGE" title="Recent observations" detail="Open an instrument to inspect its detail and chart." action={<button className="text-button" onClick={onOpenScanner}>View all <ArrowUpRight size={14} /></button>} />{loading ? <div className="skeleton-list">{[1, 2, 3, 4].map((item) => <div className="skeleton-row" key={item} />)}</div> : leaders.length ? <div className="ranking-list">{leaders.map((row) => <button className="ranking-row dashboard-level-row" key={row.symbol} onClick={() => onSelect(row.symbol)}><span className="ticker"><strong>{row.symbol}</strong><small>{row.name}</small></span><span className="row-hvtp"><small>ABOVE OPEN</small><strong>{levels(row, 'above')}</strong></span><span className="row-gap"><small>BELOW OPEN</small><strong>{levels(row, 'below')}</strong></span><span className="sector-pill">{row.sector || 'NSE'}</span><ArrowUpRight className="row-arrow" size={15} /></button>)}</div> : <div className="panel-empty">No complete level observations for this session.</div>}</section><section className="panel snapshot-panel"><SectionHeading eyebrow="SESSION COVERAGE" title="Data availability" detail="Coverage is shown separately from market direction." /><div className="coverage-ring"><strong>{total ? Math.round((available / total) * 100) : 0}%</strong><small>available</small></div><div className="snapshot-key"><span><i className="key-positive" />Reference levels <b>{available}</b></span><span><i className="key-negative" />Partial or missing <b>{missing}</b></span><span><i className="key-muted" />Current snapshots <b>{rows.filter((row) => row.currentPrice !== null).length}</b></span></div><div className="snapshot-footer"><span>Market Feed</span><strong>National Stock Exchange (NSE)</strong></div></section></div>
    <section className="panel"><SectionHeading eyebrow="CURRENT SNAPSHOTS" title="Instrument monitor" detail="Current price is informational and may be unavailable for a session." />{rows.slice(0, 6).map((row) => <button className="monitor-row" key={row.symbol} onClick={() => onSelect(row.symbol)}><span><strong>{row.symbol}</strong><small>{row.name}</small></span><b>{formatPrice(row.currentPrice)}</b><small>{formatNumber(row.totalVolume)} qty</small><DirectionValue value={row.currentVsPreviousOpen ?? null} suffix=" pts" /></button>)}</section>
  </div>
}
