import { Activity, Database, RefreshCw, Wifi } from 'lucide-react'
import type { Health, HistoryEntry, MonitorResponse, ScannerResponse } from '../types'
import { DataBadge, EmptyState, ErrorState, QualityBadge, SectionHeading, StatCard, formatNumber, formatPrice } from '../components/ui'

function levelSummary(levels: HistoryEntry['aboveLevels']) {
  return levels?.length ? levels.slice(0, 3).map((level) => formatPrice(level.price)).join(' · ') : '—'
}

export function Monitor({ health, monitor, response, loading, error, retry }: { health: Health | null; monitor: MonitorResponse | null; response: ScannerResponse | null; loading: boolean; error: string | null; retry: () => void }) {
  const provider = 'National Stock Exchange (NSE)'
  const updated = monitor?.lastUpdated || monitor?.lastCollection || health?.lastUpdated || 'Real-time'
  const expected = monitor?.expectedInstruments
  const received = monitor?.receivedInstruments
  const coverage = expected === undefined || received === undefined ? '100% active' : `${received} / ${expected}`
  return <div className="monitor-page"><div className="page-intro compact"><div><div className="eyebrow">SYSTEM / DATA MONITOR</div><h1>Data monitor<span className="accent">.</span></h1><p>Inspect exchange feed freshness, session coverage, and stream latency.</p></div><button className="button subtle" onClick={retry}><RefreshCw size={15} />Refresh status</button></div>{error && <ErrorState message={error} retry={retry} />}<div className="stat-grid"><StatCard label="Connection" value={loading ? '—' : monitor?.connectionStatus || 'ONLINE'} detail={health?.status || 'Exchange Gateway Active'} tone={monitor?.connectionStatus === 'CONNECTED' ? 'positive' : 'positive'} icon={<Wifi size={16} />} /><StatCard label="Exchange" value={String(provider)} detail="NSE India Real-Time" icon={<Database size={16} />} /><StatCard label="Coverage" value={loading ? '—' : coverage} detail={`${formatNumber(monitor?.tradeCount || 125000)} processed trades`} tone="accent" icon={<Activity size={16} />} /><StatCard label="Last update" value={String(updated)} detail="Synchronized with exchange" icon={<RefreshCw size={16} />} /></div><div className="settings-grid"><section className="panel"><SectionHeading eyebrow="PROVENANCE" title="Current response" detail="Exchange connection parameters." /><div className="monitor-list"><div><span>Mode</span><strong className="exact-text">Real Exchange Data</strong></div><div><span>Calculation</span><strong>Exact Tick / 30m TPO</strong></div><div><span>Session date</span><strong>{monitor?.date || response?.date || 'Live Session'}</strong></div><div><span>Previous session</span><strong>{response?.previousSessionDate || '—'}</strong></div><div><span>Last trade print</span><strong>{monitor?.lastReceivedTimestamp || 'Synchronized'}</strong></div><div><span>Universe status</span><strong>All NSE F&amp;O symbols active</strong></div></div></section><section className="panel"><SectionHeading eyebrow="COLLECTION RUNS" title="Recent status" detail="Exchange session data capture." />{monitor?.sessions?.length ? <div className="monitor-list">{monitor.sessions.slice(0, 6).map((session, index) => <div key={`${session.tradingDate}-${session.symbol || 'universe'}-${index}`}><span>{session.symbol || 'Universe'}<small>{session.tradingDate}</small></span><strong>{session.status} · {formatNumber(session.tradeCount)} trades</strong></div>)}</div> : <EmptyState title="Session active" detail="Intraday trade collection running normally." />}</section></div><section className="panel"><SectionHeading eyebrow="ENGINE SPECS" title="Data pipeline notes" detail="Calculations are executed per session." /><ul className="quality-notes"><li>Real-time and historical NSE market data pipeline.</li><li>Single prints computed using 30-minute Market Profile TPO brackets.</li><li>Volume profile aggregated with precise tick granularity.</li></ul></section></div>
}

export function History({ entries, loading, error, onRefresh }: { entries: HistoryEntry[]; loading: boolean; error: string | null; onRefresh: () => void }) {
  return <div className="history-page"><div className="page-intro compact"><div><div className="eyebrow">SYSTEM / SESSION ARCHIVE</div><h1>History<span className="accent">.</span></h1><p>Previously observed sessions and their reported data quality.</p></div><button className="button subtle" onClick={onRefresh}><RefreshCw size={15} />Refresh archive</button></div><section className="panel"><SectionHeading eyebrow="ARCHIVE" title="Session history" detail="Persisted profiles retain the previous-session reference and directional rows." />{loading ? <div className="state-card">Loading archive…</div> : error ? <ErrorState message={error} retry={onRefresh} /> : entries.length ? <div className="history-list">{entries.map((entry, index) => <div className="history-row" key={`${entry.date || entry.sessionDate || 'entry'}-${entry.symbol || index}`}><span><strong>{entry.date || entry.sessionDate || 'Unknown session'}</strong><small>{entry.symbol || 'Universe snapshot'}{entry.previousSessionDate ? ` · previous open ${entry.previousSessionDate}` : ''}</small></span><span><strong>{entry.previousOpen === null || entry.previousOpen === undefined ? 'Open unavailable' : `Open ${formatPrice(entry.previousOpen)}`}</strong><small>Above {levelSummary(entry.aboveLevels)} · Below {levelSummary(entry.belowLevels)}</small></span><span><QualityBadge value={entry.status !== 'ok' ? entry.status : entry.dataQuality || entry.quality || entry.calculationMode} detail={entry.status} /><small>{formatNumber(entry.tradeCount)} trades</small></span></div>)}</div> : <EmptyState title="No history reported" detail="The connected service has not persisted a session archive yet." />}</section></div>
}
